server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    return 444;
}

server {
    listen 80;
    listen [::]:80;
    server_name 147.15.97.227;

    add_header X-Robots-Tag "noindex, nofollow, noarchive, nosnippet" always;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/set-livre-acme;
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 444;
    }
}
