import {
  linkSync,
  lstatSync,
  mkdtempSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { resolve } from "node:path";

import { afterEach, describe, expect, it, vi } from "vitest";

import {
  directorySymbolicLinkType,
  fileSymbolicLinksSupported,
} from "../fixtures/filesystem-capabilities.mjs";

import { assertDatabaseGeneratedArtifactsCurrent } from "../../scripts/check-database-generated-artifacts.mjs";

const temporaryRoots = [];
const linkIt = fileSymbolicLinksSupported ? it : it.skip;
const generatedSymbolicLinkTestTitle =
  "does not follow a generated symbolic link and only removes the sibling link";
const trackedSchema = "normalized schema snapshot\n";
const trackedTypes = "export type Database = 'formatted';\n";

function databaseArtifacts() {
  const root = mkdtempSync(resolve(tmpdir(), "set-livre-generated-artifacts-check-"));
  temporaryRoots.push(root);
  const schemaDirectory = resolve(root, "supabase");
  const typesDirectory = resolve(root, "packages/contracts/src");
  mkdirSync(schemaDirectory, { recursive: true });
  mkdirSync(typesDirectory, { recursive: true });
  const schemaPath = resolve(schemaDirectory, "schema.generated.sql");
  const typesPath = resolve(typesDirectory, "database.generated.ts");
  writeFileSync(schemaPath, trackedSchema, "utf8");
  writeFileSync(typesPath, trackedTypes, "utf8");
  return { root, schemaDirectory, schemaPath, typesDirectory, typesPath };
}

function trackedIdentity(path) {
  const information = statSync(path, { bigint: true });
  return {
    ctimeNs: information.ctimeNs,
    ino: information.ino,
    mode: information.mode,
    mtimeNs: information.mtimeNs,
    size: information.size,
  };
}

function expectNoCheckTemporaries(schemaDirectory, typesDirectory) {
  expect(readdirSync(schemaDirectory)).toEqual(["schema.generated.sql"]);
  expect(readdirSync(typesDirectory)).toEqual(["database.generated.ts"]);
}

afterEach(() => {
  for (const root of temporaryRoots.splice(0)) {
    rmSync(root, { force: true, recursive: true });
  }
});

describe("generated database artifacts gate", () => {
  it("compares generated bytes from unique sibling destinations without touching tracked files", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    const schemaIdentity = trackedIdentity(schemaPath);
    const typesIdentity = trackedIdentity(typesPath);
    let generatedSchemaPath;
    let generatedTypesPath;

    await assertDatabaseGeneratedArtifactsCurrent({
      generateSchema: (destinationPath) => {
        generatedSchemaPath = destinationPath;
        expect(destinationPath).not.toBe(schemaPath);
        expect(destinationPath).toMatch(/\.schema\.generated\.sql\.check\..+\.tmp\.sql$/u);
        writeFileSync(destinationPath, trackedSchema, "utf8");
      },
      generateTypes: (destinationPath) => {
        generatedTypesPath = destinationPath;
        expect(destinationPath).not.toBe(typesPath);
        expect(destinationPath).toMatch(/\.database\.generated\.ts\.check\..+\.tmp\.ts$/u);
        writeFileSync(destinationPath, trackedTypes, "utf8");
      },
      schemaPath,
      trustedRootPath: root,
      typesPath,
    });

    expect(generatedSchemaPath).not.toBe(generatedTypesPath);
    expect(readFileSync(schemaPath, "utf8")).toBe(trackedSchema);
    expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
    expect(trackedIdentity(schemaPath)).toEqual(schemaIdentity);
    expect(trackedIdentity(typesPath)).toEqual(typesIdentity);
    expectNoCheckTemporaries(schemaDirectory, typesDirectory);
  });

  it.each([
    ["SQL", "changed schema snapshot\n", trackedTypes, "supabase/schema.generated.sql"],
    [
      "TypeScript",
      trackedSchema,
      "export type Database = 'stale';\n",
      "packages/contracts/src/database.generated.ts",
    ],
  ])(
    "fails closed when the tracked %s artifact is stale",
    async (_name, schema, types, expected) => {
      const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();

      await expect(
        assertDatabaseGeneratedArtifactsCurrent({
          generateSchema: (destinationPath) => writeFileSync(destinationPath, schema, "utf8"),
          generateTypes: (destinationPath) => writeFileSync(destinationPath, types, "utf8"),
          schemaPath,
          trustedRootPath: root,
          typesPath,
        }),
      ).rejects.toThrow(expected);

      expect(readFileSync(schemaPath, "utf8")).toBe(trackedSchema);
      expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
      expectNoCheckTemporaries(schemaDirectory, typesDirectory);
    },
  );

  it("cleans both reserved siblings and preserves tracked bytes when generation fails", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    const generateTypes = vi.fn();

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema: (destinationPath) => {
          writeFileSync(destinationPath, "partial output", "utf8");
          throw new Error("local generator failed");
        },
        generateTypes,
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("local generator failed");

    expect(generateTypes).not.toHaveBeenCalled();
    expect(readFileSync(schemaPath, "utf8")).toBe(trackedSchema);
    expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
    expectNoCheckTemporaries(schemaDirectory, typesDirectory);
  });

  linkIt("rejects a symbolic tracked artifact before invoking either generator", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    const externalPath = resolve(root, "external.sql");
    const generateSchema = vi.fn();
    const generateTypes = vi.fn();
    writeFileSync(externalPath, "external remains unchanged\n", "utf8");
    rmSync(schemaPath);
    symlinkSync(externalPath, schemaPath);

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema,
        generateTypes,
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL rastreado precisa ser um arquivo físico regular e exclusivo");

    expect(generateSchema).not.toHaveBeenCalled();
    expect(generateTypes).not.toHaveBeenCalled();
    expect(readFileSync(externalPath, "utf8")).toBe("external remains unchanged\n");
    expect(readdirSync(schemaDirectory)).toEqual(["schema.generated.sql"]);
    expect(readdirSync(typesDirectory)).toEqual(["database.generated.ts"]);
  });

  it("rejects a hard-linked tracked artifact before invoking either generator", async () => {
    const { root, schemaPath, typesPath } = databaseArtifacts();
    const secondLink = resolve(root, "second-schema-link.sql");
    const generateSchema = vi.fn();
    const generateTypes = vi.fn();
    linkSync(schemaPath, secondLink);

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema,
        generateTypes,
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL rastreado precisa ser um arquivo físico regular e exclusivo");

    expect(generateSchema).not.toHaveBeenCalled();
    expect(generateTypes).not.toHaveBeenCalled();
    expect(readFileSync(secondLink, "utf8")).toBe(trackedSchema);
  });

  it("fails if a tracked artifact changes while the generators are running", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema: (destinationPath) => writeFileSync(destinationPath, trackedSchema, "utf8"),
        generateTypes: (destinationPath) => {
          writeFileSync(destinationPath, trackedTypes, "utf8");
          writeFileSync(schemaPath, "concurrent tracked mutation\n", "utf8");
        },
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL rastreado mudou durante o gate");

    expect(readFileSync(schemaPath, "utf8")).toBe("concurrent tracked mutation\n");
    expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
    expectNoCheckTemporaries(schemaDirectory, typesDirectory);
  });

  it("fails if the first generated result changes during the second generation", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    let generatedSchemaPath;

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema: (destinationPath) => {
          generatedSchemaPath = destinationPath;
          writeFileSync(destinationPath, trackedSchema, "utf8");
        },
        generateTypes: (destinationPath) => {
          writeFileSync(generatedSchemaPath, "concurrent generated mutation\n", "utf8");
          writeFileSync(destinationPath, trackedTypes, "utf8");
        },
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL verificado mudou durante o gate");

    expect(readFileSync(schemaPath, "utf8")).toBe(trackedSchema);
    expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
    expectNoCheckTemporaries(schemaDirectory, typesDirectory);
  });

  it("rejects a symbolic directory ancestor without creating output beyond it", async () => {
    const { root, schemaDirectory, schemaPath, typesPath } = databaseArtifacts();
    const externalDirectory = resolve(root, "external-schema");
    const generateSchema = vi.fn();
    const generateTypes = vi.fn();
    rmSync(schemaDirectory, { recursive: true });
    mkdirSync(externalDirectory);
    writeFileSync(resolve(externalDirectory, "schema.generated.sql"), trackedSchema, "utf8");
    symlinkSync(externalDirectory, schemaDirectory, directorySymbolicLinkType);

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema,
        generateTypes,
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL rastreado exige diretórios ancestrais físicos");

    expect(generateSchema).not.toHaveBeenCalled();
    expect(generateTypes).not.toHaveBeenCalled();
    expect(readdirSync(externalDirectory)).toEqual(["schema.generated.sql"]);
  });

  it("tries both non-recursive cleanups without masking the generation error", async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    let generatedSchemaPath;
    let rejection;

    try {
      await assertDatabaseGeneratedArtifactsCurrent({
        generateSchema: (destinationPath) => {
          generatedSchemaPath = destinationPath;
          rmSync(destinationPath);
          mkdirSync(destinationPath);
          throw new Error("local generator failed");
        },
        generateTypes: vi.fn(),
        schemaPath,
        trustedRootPath: root,
        typesPath,
      });
    } catch (error) {
      rejection = error;
    }

    expect(rejection).toBeInstanceOf(AggregateError);
    expect(rejection.message).toBe("local generator failed");
    expect(rejection.errors).toHaveLength(2);
    expect(lstatSync(generatedSchemaPath).isDirectory()).toBe(true);
    expect(readdirSync(typesDirectory)).toEqual(["database.generated.ts"]);
    expect(readdirSync(schemaDirectory)).toContain("schema.generated.sql");
  });

  linkIt(generatedSymbolicLinkTestTitle, async () => {
    const { root, schemaDirectory, schemaPath, typesDirectory, typesPath } = databaseArtifacts();
    const externalPath = resolve(root, "external-generated.sql");
    writeFileSync(externalPath, "external remains unchanged\n", "utf8");

    await expect(
      assertDatabaseGeneratedArtifactsCurrent({
        generateSchema: (destinationPath) => {
          rmSync(destinationPath);
          symlinkSync(externalPath, destinationPath);
        },
        generateTypes: (destinationPath) => writeFileSync(destinationPath, trackedTypes, "utf8"),
        schemaPath,
        trustedRootPath: root,
        typesPath,
      }),
    ).rejects.toThrow("snapshot SQL verificado precisa ser um arquivo físico regular e exclusivo");

    expect(readFileSync(externalPath, "utf8")).toBe("external remains unchanged\n");
    expect(readFileSync(schemaPath, "utf8")).toBe(trackedSchema);
    expect(readFileSync(typesPath, "utf8")).toBe(trackedTypes);
    expectNoCheckTemporaries(schemaDirectory, typesDirectory);
  });
});
